name: Kittygram

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for backend
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0 
          pip install -r backend/requirements.txt

      - name: Lint backend with flake8
        run: |
          python -m flake8 backend/

      - name: Run backend tests
        run: |
          cd backend
          python manage.py test

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
