volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend